import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { IInvoice } from '../models/invoice.model';

const THEME = {
  primary: '#0F766E', // Teal
  accent: '#14B8A6',
  dark: '#1E293B',
  text: '#334155',
  muted: '#64748B',
  border: '#E2E8F0',
  bgLight: '#F8FAFC',
  bgHeader: '#F1F5F9',
  alert: '#EF4444',
  white: '#FFFFFF',
};

// Robust font resolver
const pickFirstExisting = (paths: string[]) => {
  for (const p of paths) {
    if (fs.existsSync(p)) return p;
  }
  return null;
};

export const generateInvoicePdf = async (invoice: IInvoice, businessName: string, logoPath?: string): Promise<string> => {
  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 50, bottom: 50, left: 40, right: 40 },
    bufferPages: true,
    autoFirstPage: true,
  });

  const filename = `invoice-${invoice.invoiceNumber}.pdf`;
  const tempFilePath = path.join(process.cwd(), 'public', 'reports', filename);
  const dir = path.dirname(tempFilePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const stream = fs.createWriteStream(tempFilePath);
  doc.pipe(stream);

  // Fonts
  const notoPath = pickFirstExisting([
    path.join(process.cwd(), 'assets', 'fonts', 'NotoSans-Regular.ttf'),
    '/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf',
    '/usr/share/fonts/opentype/noto/NotoSans-Regular.ttf',
  ]);

  if (notoPath) {
    doc.registerFont('Regular', notoPath);
    doc.registerFont('Bold', notoPath);
  } else {
    doc.registerFont('Regular', 'Helvetica');
    doc.registerFont('Bold', 'Helvetica-Bold');
  }

  const pageWidth = doc.page.width;
  const margin = doc.page.margins.left;
  const contentWidth = pageWidth - margin * 2;

  // --- HEADER ---
  // Business Name (Large & Bold)
  doc.fillColor(THEME.primary).font('Bold').fontSize(20).text(businessName.toUpperCase(), margin, 50);
  doc.fillColor(THEME.muted).font('Regular').fontSize(10).text('INVOICE', margin, 75);

  // Logo (Right Aligned)
  if (logoPath && fs.existsSync(logoPath)) {
      doc.image(logoPath, pageWidth - margin - 60, 50, { width: 60, height: 60 });
  } else {
      // Clean text placeholder if no logo
      doc.fillColor(THEME.muted).fontSize(10).text('Generated by TallyPadi', pageWidth - margin - 120, 55, { align: 'right' });
  }
  
  // Separator Line
  doc.moveTo(margin, 100).lineTo(pageWidth - margin, 100).strokeColor(THEME.border).stroke();

  // --- META INFO ---
  const metaY = 120;
  
  // Left: Bill To
  doc.fillColor(THEME.muted).fontSize(9).text('BILL TO', margin, metaY);
  doc.fillColor(THEME.dark).font('Bold').fontSize(12).text(invoice.customerName, margin, metaY + 15);
  
  // Right: Invoice Details (Aligned properly)
  const rightColX = pageWidth - margin - 150;
  doc.fillColor(THEME.muted).font('Regular').fontSize(9).text('Invoice No:', rightColX, metaY);
  doc.fillColor(THEME.dark).font('Bold').fontSize(10).text(invoice.invoiceNumber, rightColX + 60, metaY, { align: 'right', width: 90 });

  doc.fillColor(THEME.muted).font('Regular').fontSize(9).text('Date:', rightColX, metaY + 15);
  doc.fillColor(THEME.dark).font('Bold').fontSize(10).text(new Date(invoice.dateIssued).toLocaleDateString(), rightColX + 60, metaY + 15, { align: 'right', width: 90 });

  // --- TABLE HEADER ---
  const tableTop = 190;
  const colX = {
      desc: margin + 10,
      qty: margin + 270,
      price: margin + 340,
      total: margin + 430
  };
  const colW = {
      desc: 250,
      qty: 60,
      price: 80,
      total: 80
  };

  // Header Background
  doc.rect(margin, tableTop, contentWidth, 25).fill(THEME.bgHeader);
  
  // Header Text
  doc.fillColor(THEME.dark).font('Bold').fontSize(9);
  doc.text('ITEM DESCRIPTION', colX.desc, tableTop + 8);
  doc.text('QTY', colX.qty, tableTop + 8, { align: 'center', width: colW.qty });
  doc.text('PRICE', colX.price, tableTop + 8, { align: 'right', width: colW.price });
  doc.text('TOTAL', colX.total, tableTop + 8, { align: 'right', width: colW.total });

  // --- TABLE ROWS ---
  let y = tableTop + 30;
  doc.font('Regular').fontSize(10);

  invoice.items.forEach((item, i) => {
      // Zebra striping
      if (i % 2 !== 0) doc.rect(margin, y - 5, contentWidth, 20).fill(THEME.bgLight);

      doc.fillColor(THEME.text);
      doc.text(item.name, colX.desc, y, { width: colW.desc, lineBreak: false, ellipsis: true });
      doc.text(String(item.qty), colX.qty, y, { width: colW.qty, align: 'center' });
      doc.text(item.unitPrice.toLocaleString(), colX.price, y, { width: colW.price, align: 'right' });
      doc.text(item.total.toLocaleString(), colX.total, y, { width: colW.total, align: 'right' });
      
      y += 25; // Row height
  });

  // Divider
  doc.moveTo(margin, y).lineTo(pageWidth - margin, y).strokeColor(THEME.border).stroke();
  y += 15;

  // --- TOTALS SECTION ---
  const totalBoxX = pageWidth - margin - 200;
  
  doc.font('Bold').fontSize(12).fillColor(THEME.dark);
  doc.text('Total Amount:', totalBoxX, y, { width: 100, align: 'right' });
  doc.fillColor(THEME.primary).fontSize(14);
  doc.text(invoice.totalAmount.toLocaleString(), totalBoxX + 110, y - 2, { width: 90, align: 'right' });

  // --- BANK DETAILS (Styled Box) ---
  if (invoice.bankDetailsSnapshot) {
      const bankBoxY = y + 50;
      // Background Box with Border
      doc.rect(margin, bankBoxY, 250, 70).fillAndStroke(THEME.bgLight, THEME.border);
      
      doc.fillColor(THEME.primary).font('Bold').fontSize(9).text('PAYMENT DETAILS', margin + 15, bankBoxY + 15);
      
      doc.fillColor(THEME.dark).font('Regular').fontSize(10);
      doc.text(invoice.bankDetailsSnapshot.bankName, margin + 15, bankBoxY + 30);
      
      doc.font('Bold').fontSize(11);
      doc.text(invoice.bankDetailsSnapshot.accountNumber, margin + 15, bankBoxY + 45);
      
      doc.font('Regular').fontSize(9).fillColor(THEME.muted);
      doc.text(invoice.bankDetailsSnapshot.accountName, margin + 15, bankBoxY + 58);
  }

  // --- FOOTER ---
  const footerY = doc.page.height - 60;
  doc.fontSize(9).fillColor(THEME.muted).text('Thank you for your business.', 0, footerY, { align: 'center' });
  doc.fontSize(8).text('Generated via TallyPadi', 0, footerY + 15, { align: 'center' });

  doc.end();

  return new Promise((resolve, reject) => {
    stream.on('finish', () => resolve(filename));
    stream.on('error', reject);
  });
};
