// src/controllers/receipt.controller.ts
import { Request, Response } from 'express';
import PDFDocument from 'pdfkit';
import { Transaction } from '../models/transaction.model';
import { User } from '../models/user.model';

function toUserLocalDate(d: any, offsetMinutes: number) {
  return new Date(new Date(d).getTime() + offsetMinutes * 60_000);
}

// ✅ REQUIRED FORMAT: 22/12/2025 14:05
function fmtDDMMYYYY_HHMM(d: Date, offsetMinutes: number) {
  const local = toUserLocalDate(d, offsetMinutes);
  const dd = String(local.getDate()).padStart(2, '0');
  const mm = String(local.getMonth() + 1).padStart(2, '0');
  const yyyy = String(local.getFullYear());
  const hh = String(local.getHours()).padStart(2, '0');
  const min = String(local.getMinutes()).padStart(2, '0');
  return `${dd}/${mm}/${yyyy} ${hh}:${min}`;
}

export const generateSaleReceiptPdf = async (req: Request | any, res: Response) => {
  try {
    const userId = req.user?.id || req.user?._id;
    if (!userId) return res.status(401).json({ error: 'Unauthorized' });

    const saleId = String(req.params.saleId || '').trim();
    if (!saleId) return res.status(400).json({ error: 'Missing saleId' });

    const user = await User.findById(userId).lean();
    if (!user) return res.status(404).json({ error: 'User not found' });

    // ✅ Optional: enforce TYCOON only (uncomment if you want)
    // if (String((user as any).planType || '').toUpperCase() !== 'TYCOON') {
    //   return res.status(403).json({ error: 'Upgrade to Tycoon to print receipt' });
    // }

    const tx: any = await Transaction.findOne({
      _id: saleId,
      user: userId,
      type: 'SALE',
      isUndone: { $ne: true },
    }).lean();

    if (!tx) return res.status(404).json({ error: 'Sale not found' });

    const offsetMinutes = (user as any)?.settings?.utcOffsetMinutes ?? 60;
    const businessName = (user as any)?.businessName || 'My Shop';

    const currencyCode = (user as any)?.currencyCode || 'NGN';
    const locale = (user as any)?.locale || 'en-NG';

    const formatMoney = (n: any) =>
      new Intl.NumberFormat(locale, { style: 'currency', currency: currencyCode, maximumFractionDigits: 0 }).format(
        Number(n || 0)
      );

    const receiptDate = fmtDDMMYYYY_HHMM(new Date(tx.timestamp || tx.createdAt || Date.now()), offsetMinutes);

    // ✅ PDF
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=Receipt_${saleId}.pdf`);

    const doc = new PDFDocument({ size: 'A4', margins: { top: 40, bottom: 40, left: 40, right: 40 } });
    doc.pipe(res);

    // Header
    doc.fontSize(18).text('TallyPadi Receipt', { align: 'left' });
    doc.moveDown(0.3);
    doc.fontSize(11).fillColor('#334155').text(businessName);
    doc.fillColor('#000000');
    doc.fontSize(10).text(`Receipt Date: ${receiptDate}`);
    doc.fontSize(10).text(`Sale ID: ${saleId}`);
    doc.moveDown(1);

    // Items table header
    doc.fontSize(11).text('Items Sold', { underline: true });
    doc.moveDown(0.5);

    const items = Array.isArray(tx.items) ? tx.items : [];
    items.forEach((it: any, idx: number) => {
      const qty = Number(it.qty ?? it.quantity ?? 0);
      const name = String(it.name || 'Item');
      const unitPrice = Number(it.unitPrice ?? it.price ?? 0);
      const lineTotal = Number(it.total ?? qty * unitPrice);

      doc.fontSize(10).text(`${idx + 1}. ${name}`);
      doc.fontSize(10).fillColor('#475569').text(`   ${qty} × ${formatMoney(unitPrice)}  =  ${formatMoney(lineTotal)}`);
      doc.fillColor('#000000');
      doc.moveDown(0.3);
    });

    doc.moveDown(0.8);
    doc.moveTo(doc.page.margins.left, doc.y).lineTo(doc.page.width - doc.page.margins.right, doc.y).stroke();
    doc.moveDown(0.6);

    const totalMoney = Number(tx.totalMoney || 0);
    doc.fontSize(12).text(`TOTAL: ${formatMoney(totalMoney)}`, { align: 'right' });

    doc.moveDown(1.2);
    doc.fontSize(9).fillColor('#64748b').text('Generated by TallyPadi', { align: 'center' });

    doc.end();
  } catch (e: any) {
    console.error('Receipt PDF Error:', e?.stack || e);
    if (!res.headersSent) res.status(500).json({ error: 'Could not generate receipt' });
  }
};
